### PR TITLE
hal: nuvoton: m2l31: fixed TRUE/FALSE redefined warning

### PR DESCRIPTION
**Pull request by cyliangtw**
This PR is to fix redefined warnings of TRUE/FALSE in M2L31.h

### CODE REVIEW

**Comment by fabiobaltieri** [comment]
bit confusing... what does this collide with?

**Comment by cyliangtw** [comment]
$ `west build -p auto -b numaker_m2l31ki ./samples/subsys/portability/cmsis_rtos_v2/timer_synchronization/`

got: 
```
C:/Zephyr_rtos/modules/hal/nuvoton/m2l31x/Devices/M2L31/Include/M2L31.h:725: note: this is the location of the previous definition
  725 | #define TRUE          (1UL)                ///< Boolean true, define to use in API parameters or return value
      |
C:/Zephyr_rtos/zephyr/subsys/portability/cmsis_rtos_v2/wrapper.h:14: warning: "FALSE" redefined
   14 | #define FALSE   0

```

**Comment by cyliangtw** [comment]
This twister build of  [zephyr PR #73886](https://github.com/zephyrproject-rtos/zephyr/pull/73886) failed, so I modified it.
This PR could resolve this warnings and I applied it in commit 8a2b5de1670b59f for M467 last year.

**Comment by fabiobaltieri** [comment]
I see, how about matching the define instead? that should make the compiler happy as well and be a bit less intrusive, like: drop the UL suffix

**Comment by cyliangtw** [comment]
some SDK functions need TRUE/FALSE and want to avoid redefine warnings in zephyr header files. More, there is no UL suffix in enum { FALSE, TRUE };

You mean ...

**Comment by cyliangtw** [comment]
The use case of https://github.com/zephyrproject-rtos/zephyr/pull/73886, the test code include M2L31.h before include ./subsys/portability/cmsis_rtos_v2/wrapper.h:
```
#include <zephyr/kernel.h>
#include <cmsis_os2.h>

#define TRUE    1
#define FALSE   0

```
So, I use alternative enum instead of #define

**Comment by cyliangtw** [comment]
OK, I see 
to set the same define of  ./subsys/portability/cmsis_rtos_v2/wrapper.h to avoid re-define warning

**Comment by fabiobaltieri** [comment]
Yeah, no ideal solution to be honest but the enum looked a bit weird

**Review by fabiobaltieri — APPROVED** [review]

**Comment by danieldegrasse** [comment]
@cyliangtw I'll pull this into https://github.com/zephyrproject-rtos/zephyr/pull/73886, if that's ok- thank you for the fix!

**Comment by fabiobaltieri** [comment]
@danieldegrasse this should be in the upstream manifest now, just rebase whatever you need on top of main

**Pull request merged**
