### PR TITLE
hal: nuvoton: add nuvoton numicro m480 series hal library

### PR DESCRIPTION
**Pull request by ssekar15**
Add v3.05.000 as initial version of nuvoton numicro hal library with M480 SoC series support.
    
M480 BSP Stdriver and Device support is organized in favour of Zephyr.
    
Origin: Nuvoton numicro m480 BSP
URL: https://github.com/OpenNuvoton/M480BSP
Version: v3.05.000 (SHA: 54ffafdee1fabe8316e19143201755b6f61e6ffc)
Purpose: Add support for Numicro M48x SoCs
Maintained-by: External

### CODE REVIEW

**Comment by ssekar15** [comment]
@carlescufi Please review

**Review by carlescufi — APPROVED** [review]
Scanned for licenses with scancode toolkit, everything in the PR is Apache-2.0.

Result attached (it is html renamed to txt).
[nuvoton.txt](https://github.com/zephyrproject-rtos/hal_nuvoton/files/4815619/nuvoton.txt)

**Comment by carlescufi** [comment]
@ssekar15 please post a PR to the main zephyr repo that uses this PR.

**Review by jettr — APPROVED** [review]
Looks fine to me. Nothing jumps out.

**Comment by MulinChao** [comment]
LGTM. No comments from Nuvoton.

**Review by MulinChao — APPROVED** [review]

**Comment by MulinChao** [comment]
Oops. Hope I didn't do anything wrong.

**Pull request merged**
